### ISSUE TITLE
ERROR: No module named 'openpype'

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [ynput/ayon-djv#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

we need to fix the dependencies . . .

### Version

1.0.0

### What platform you are running on?

Windows

### Steps To Reproduce:

just run the ayon_console

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Relevant log output:

```shell
*** WRN: >>> { AddonsLoader }: [  FAILED to import "ayon_djv"  ]
==========================
No module named 'openpype'
==========================
Traceback (most recent call last):
  File "C:\Users\murph\AppData\Local\Ynput\AYON\addons\core_1.0.1\ayon_core\addon\base.py", line 338, in _load_ayon_addons
    mod = __import__(basename, fromlist=("",))
  File "C:\Users\murph\AppData\Local\Ynput\AYON\addons\djv_1.0.0\ayon_djv\__init__.py", line 2, in <module>
    from .addon import DJVAddon
  File "C:\Users\murph\AppData\Local\Ynput\AYON\addons\djv_1.0.0\ayon_djv\addon.py", line 2, in <module>
    from openpype.modules import AYONAddon, IPluginPaths
ModuleNotFoundERROR: No module named 'openpype'
```

**Comment by iLLiCiTiT** [comment]
Update to version 1.1.0 . Closing.

**Comment by m-u-r-p-h-y** [comment]
can we push it to Addon Market so we do not have to chase the updates individually on github?
